manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      repo-path: zephyr
      clone-depth: 1
      revision: main
      import: true
      path: zephyr

  self:
    path: test_picolib
